name: Multi-Universe Pairs Scanner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * *'  # Daily at 22:00 UTC

jobs:
  scan-universe:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        universe:
          - tech_core
          - semis
          - software
          - financials
          - healthcare
          - discretionary
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create results directory
        run: mkdir -p results
      
      - name: Run scanner for ${{ matrix.universe }}
        run: |
          python scan_pairs_multi.py \
            --universe ${{ matrix.universe }} \
            --start-date 2018-01-01 \
            --auto-adjust \
            --coint-lookbacks 240,300 \
            --min-sample 200 \
            --topk 100 \
            --out-dir results
      
      - name: Verify output files
        run: |
          echo "Checking results for ${{ matrix.universe }}..."
          ls -la results/${{ matrix.universe }} || true
          if [ -f "results/${{ matrix.universe }}/${{ matrix.universe }}_candidates.csv" ]; then
            echo "✓ Candidates file created"
            wc -l results/${{ matrix.universe }}/${{ matrix.universe }}_candidates.csv
          else
            echo "⚠ No candidates file found"
          fi
      
      - name: Upload universe results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.universe }}
          path: results/${{ matrix.universe }}/
          if-no-files-found: warn
          retention-days: 30

  aggregate-results:
    needs: scan-universe
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Download all universe results
        uses: actions/download-artifact@v4
        with:
          path: results/
          pattern: results-*
          merge-multiple: false
      
      - name: Reorganize downloaded artifacts
        run: |
          echo "Reorganizing artifact structure..."
          mkdir -p results_final
          for universe in tech_core semis software financials healthcare discretionary; do
            if [ -d "results/results-${universe}/${universe}" ]; then
              echo "Moving results-${universe}/${universe} to results_final/${universe}"
              mv "results/results-${universe}/${universe}" "results_final/${universe}"
            elif [ -d "results/results-${universe}" ]; then
              echo "Moving results-${universe} to results_final/${universe}"
              mv "results/results-${universe}" "results_final/${universe}"
            fi
          done
          echo "Final structure:"
          ls -la results_final/
      
      - name: Aggregate all results
        run: |
          python run_all_and_aggregate.py \
            --topn 150 \
            --out-dir results_final \
            --skip-scan
      
      - name: Verify aggregated files
        run: |
          echo "Checking aggregated results..."
          ls -la results_final/ || true
          if [ -f "results_final/combined_pairs_scored.csv" ]; then
            echo "✓ Combined scores file created"
            wc -l results_final/combined_pairs_scored.csv
          fi
          if [ -f "results_final/combined_top150_watchlist.csv" ]; then
            echo "✓ Watchlist file created"
            wc -l results_final/combined_top150_watchlist.csv
          fi
      
      - name: Upload all candidates files
        uses: actions/upload-artifact@v4
        with:
          name: all-candidates
          path: results_final/**/*_candidates.csv
          if-no-files-found: error
          retention-days: 90
      
      - name: Upload all metrics files
        uses: actions/upload-artifact@v4
        with:
          name: all-metrics
          path: results_final/**/*_all_metrics.csv
          if-no-files-found: error
          retention-days: 30
      
      - name: Upload combined results
        uses: actions/upload-artifact@v4
        with:
          name: combined-results
          path: |
            results_final/combined_pairs_scored.csv
            results_final/combined_top150_watchlist.csv
          if-no-files-found: error
          retention-days: 90